### ISSUE TITLE
Initial theme

### ISSUE THREAD

**Issue by nesl247** [dracula/brackets#1]
Pinging @felipekm from https://github.com/dracula/dracula-theme/pull/45.

**Comment by zenorocha** [comment]
Hey @felipekm, are you still using Brackets with Dracula? Are you interested in contributing?

**Comment by felipekm** [comment]
Hey @zenorocha, actually I'm not.
But I would happy to contribute, totally forgot that need in dracula/dracula-theme#45.

**Comment by felipekm** [comment]
Just raised the PR: https://github.com/dracula/brackets/pull/2

I'd like to point that there other Brackets Theme registered named `Dracula`, I name ours to `Dracula Zeno Rocha`, let me know if other name is better.

![image](https://cloud.githubusercontent.com/assets/205932/23193052/a97f98b4-f885-11e6-87a5-c83d7cd3eae7.png)

Repo: https://github.com/NetOperatorWibby/DraculaBrackets

More details on my [PR](https://github.com/dracula/brackets/pull/2).

**Comment by zenorocha** [comment]
Closing this one since #2 was merged!

**Comment by zenorocha** [comment]
https://draculatheme.com/brackets

https://github.com/dracula/dracula.github.io/commit/f8eb910b1b6d800db28fe2eaa9b3bdfbba8b883a
https://github.com/dracula/brackets/commit/f1f9b1f312763f65ccdece6a779e15f2c4a4b311
