### ISSUE TITLE
Scroll bar is very hard to detect

### ISSUE THREAD

**Issue by rogierlegit** [dracula/brackets#7]
Especially in long files when the icon is very small. Maybe it should be a lighter color than the background instead of darker? That's how Dracula for VS code does it.

<img width="835" alt="Schermafbeelding 2023-11-21 om 12 04 00" src="https://github.com/dracula/brackets/assets/117164486/fd6b74d1-a2ad-4895-8125-f973f028e0e4">

**Comment by felipekm** [comment]
Hey @rogierlegit are you still using Brackets?

**Comment by rogierlegit** [comment]
Yes, sometimes. Not as often as I used to, and I switched back to the light theme for the default.

**Comment by felipekm** [comment]
Hey @rogierlegit, does it look better for you?

![image](https://github.com/user-attachments/assets/62ce2892-920b-46d7-bad3-82766730fb44)

**Comment by felipekm** [comment]
@rogierlegit,

The Brackers extension registry seems not to be working properly.
If you want to use the new version, add this URL:

`https://github.com/dracula/brackets/archive/refs/tags/v1.0.1.zip`

![image](https://github.com/user-attachments/assets/7172ef5a-27cf-4120-b447-4180f32e2766)
